all:  TestApp RMIservice Peer Backup Chunk MyFile Channel ChannelThread Delete Reclaim Restore Utils

TestApp:
	javac TestApp.java
RMIservice:
	javac RMIservice.java
Peer:
	javac Peer.java
Backup:
	javac Backup.java
Chunk:
	javac Chunk.java
MyFile:
	javac MyFile.java
Channel:
	javac Channel.java
ChannelThread:
	javac ChannelThread.java
Delete:
	javac Delete.java
Reclaim:
	javac Reclaim.java
Restore:
	javac Restore.java
Utils:
	javac Utils.java
clean:
	rm -rf *class TestApp RMIservice Peer Backup Chunk MyFile Channel ChannelThread Delete Reclaim Restore Utils

