all:  TestApp BackupService Peer Backup Chunk MyFile

TestApp:
	javac TestApp.java
BackupService:
	javac BackupService.java
Peer:
	javac Peer.java
Backup:
	javac Backup.java
Chunk:
	javac Chunk.java
MyFile:
	javac MyFile.java
clean:
	rm -rf *class TestApp BackupService Peer Backup Chunk MyFile

